### ISSUE TITLE
Depth extension not working with UNSIGNED_SHORT

### ISSUE THREAD

**Issue by mattdesl** [stackgl/gl-fbo#10]
When extension is present, FBO rendering is not including depth information. However, switching the texture format to UNSIGNED_INT works fine.

Will investigate and put together a reproducible example..

**Comment by mikolalysenko** [comment]
Thanks, let me know what you find.

**Comment by mattdesl** [comment]
I can't reproduce the issue anymore. I think it was some odd combination of GL states causing it to happen, and not a browser bug.
