### ISSUE TITLE
Framebuffer incomplete attachment in Safari

### ISSUE THREAD

**Issue by dy** [stackgl/gl-fbo#17]
``` js
var createFBO = require("gl-fbo")
var gl = document.createElement('canvas').getContext('webgl')

createFBO(gl, [512, 512], {preferFloat: true})
```

Gives 

```
Error: gl-fbo: Framebuffer incomplete attachment
```

That is one of the reasons why plotly does not plot in iOS https://github.com/plotly/plotly.js/issues/280.
Possibly related to #14.

**Comment by dy** [comment]
Ok, [seems that](http://stackoverflow.com/a/28949220/1052640) iOS just does not allow rendering to floating point textures.

**Comment by eyworldwide** [comment]
I encounter the same problem when i use `gl-particle`:

https://github.com/stackgl/gl-particles/blob/master/index.js#L40

```
this.prev = FBO(gl, [this.shape[0], this.shape[1]], { float: true })
this.curr = FBO(gl, [this.shape[0], this.shape[1]], { float: true })
```

**Comment by mikolalysenko** [comment]
iOS Safari doesn't support floating point textures because it is a terrible browser.  Not much can be done to fix this until Apple gets their shit together.
